### ISSUE TITLE
how to test socket.io

### ISSUE THREAD

**Issue by yuu2lee4** [plantain-00/ws-benchmark#1]
how to test socket.io

**Comment by plantain-00** [comment]
`socket.io`'s websocket protocol url is something like: `ws://localhost:8080/socket.io/?transport=websocket`, so just test that url

**Comment by yuu2lee4** [comment]
I use like this `ws-benchmark ws://localhost:7001/socket.io/?transport=websocket -c 10 -n 20`, it tell me `no matches found: ws://localhost:7001/socket.io/?transport=websocket`, i change it like this `ws-benchmark ws://localhost:7001/socket.io  -c 10 -n 20`, it throw a `socket hang up` Error

**Comment by plantain-00** [comment]
It seems like: `ws-benchmark "ws://localhost:7001/socket.io/?transport=websocket" -c 10 -n 20`, I will update the document.

**Comment by yuu2lee4** [comment]
It can be excuted,but my server has no sign for connecting,how to prove my serve has really been connected.

**Comment by plantain-00** [comment]
When it connected to socket.io server, it should be in the 'connection' event
It sends message "Hello world!" by default, you can add '-f a.json' to send a custom message

**Comment by plantain-00** [comment]
socket.io message looks like:
```text
42["test",{"username":"hello","message":"world"}]
```
Then your server can get it in 'test' event

**Comment by yuu2lee4** [comment]
how to specify namespace of socket.io

**Comment by yuu2lee4** [comment]
我看你也是中国人 我就写中文了，socket服务端代码：
````javascript
import { Application } from 'egg';

let n = 0;

export default (app: Application) => {
  (app.io as any).on('connection', function(socket){
    n++;
    console.log(`${n} connected`);
    socket.on('test', (data) => {
      console.log(`${n} data:`, data);
    });
  });
};
````
我执行 `ws-benchmark "ws://localhost:7001/socket.io/?transport=websocket" -c 10 -n 2000`,结果是:
````javascript
1 connected
2 connected
3 connected
4 connected
5 connected
6 connected
7 connected
8 connected
9 connected
10 connected
````
只有10次连接，然后没监听到test消息

**Comment by plantain-00** [comment]
默认发送的是 "hello world!" 字符串，socket.io 识别不了，你把 `42["test",{"username":"hello","message":"world"}]` 保存为一个文件，例如 a.txt，然后 `ws-benchmark "ws://localhost:7001/socket.io/?transport=websocket" -c 10 -n 2000 -f a.txt`

**Comment by yuu2lee4** [comment]
ok  我试试 但是还是有以下两个问题：
1、连接数不对
2、namespace如何测试有方法么

**Comment by plantain-00** [comment]
你可以看下文档，`-c 10` 就是并行请求，也就是 10 个连接，`-n 2000` 是一共发 2000 个请求，每个连接平均 200 个请求，这些参数和 apachbench 是一致的。
至于 namespace，多个 namespace 是共用一个 websocket 连接的，namespace 应该不影响结果，至于 namespace 怎么测，我就不清楚了。

**Comment by yuu2lee4** [comment]
10个连接是socket还是2000个请求是， 如果2000是，那一个socket就会触发一个connection，那看来10才是socket 2000代表什么请求？ 是代表每个socket emit200次消息？

**Comment by plantain-00** [comment]
+ -c: Number of multiple requests to make at a time(the count of http clients or websocket connections)，对于 websocket，是 websocket connection 数
+ -n: Number of requests to perform，对于 websocket ，是发送的 message 总数，由各个 connection 平分
